### ISSUE TITLE
HTTP Basic Auth Username variable

### ISSUE THREAD

**Issue by dikeckaan** [Frederic-Boulanger-UPS/docker-ubuntu_22-04-novnc#2]
Hello,

I loved  this repo but i cant find or edite http auth username variable.

![image](https://user-images.githubusercontent.com/21171681/216773720-704e1213-c534-46aa-88b9-ed0e9e8c10a0.png)

please help me,

Best Regards.

**Comment by Frederic-Boulanger-UPS** [comment]
Hello,

The username is set by the USERNAME environment variable and defaults to root.
So if you started the container with 'docker run -p 6080:80 -e HTTP_PASSWORD=mypassword fredblgr/ubuntu-novnc:22.04', you should put "root" in the Username field, and "mypassword" in the Password field.

Best regards.
